---
- name: This copy a sh file and run it in remote machine
  hosts: web
  vars:
    myname: "Meera in Playbook"
    package: "httpd"
    service: "httpd"
  tasks:
  - name: copy a script file
    copy: dest=/tmp src="script.sh"
  - name: change the permission
    file:
     path: /tmp/script.sh
     mode: 0775
  - name: execute the script file
    script: /tmp/script.sh
...
