---
- name: This sets up an httpd webserver
  hosts: db
  vars:
    myname: "hpe ansible training-Playbook"
    package: "httpd"
    service: "httpd"
  tasks:
  - name: Install the httpd apps
    yum: name={{ package }}
  - name: start the httpd service
    service: name={{ service }} state=started
  - name: create a empty fle
    file: dest=/home/test.txt state=touch
  - name: copy a file
    copy: dest=/var/www/html/ src="/root/index.html"
  - name: Ansible prompt example.
    debug:
      msg: "{{ myname }}"
...
