---
- name: Setup httpd webserver
  hosts: web
  tasks:
  - name: Template a file to /etc/httpd/conf/httpd.conf
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - restart apache
  - name: Install the httpd
    yum: name={{ package }}
  - name: start the httpd service
    service: name={{ service }} state=started
  - name: copy a file
    copy: src="/root/index.html" dest=/var/www/html
  - name: Ansible prompt example.
    debug:
      msg: "{{ myname }}"
  handlers:
  - name: restart apache
    service: name=httpd state=restarted
...
