---
- name: This sets up an httpd webserver
  hosts: web
  tasks:
  - name: copy a file
    copy: dest=/var/www/html/ src="/root/kavitha/script.sh"
  - name: change the permissions of the file
    file: path=/var/www/html/script.sh mode='777'
  - name: create the script
    script: /var/www/html/script.sh
...