---
- name: MY playbook with variables
  hosts: db
  vars:
    package: "httpd"
    service: "httpd"
  tasks:
  - name: Install the httpd apps
    yum: name={{ package }}
  - name: start the httpd service
    service: name={{ service }} state=started  
...