---
- name: MY playbook with variables in inventory
  hosts: db
  tasks:
  - name: Install the httpd apps
    yum: name={{ package }}
  - name: start the httpd service
    service: name={{ service }} state=started  
...