---
- name: MY playbook with variables in external file
  hosts: db
  vars_files: 
  - "Externalfile.yaml"
  tasks:
  - name: Install the httpd apps
    yum: name={{ package }}
  - name: start the httpd service
    service: name={{ service }} state=started  
...