- hosts: gog
  gather_facts: no
  tasks:
  - name: Create index.html
    file:
       path: /var/www/html/index.html
       state: touch
  - name: update index.html
    lineinfile:
       path: /var/www/html/index.html
       state: present
       line: 'My Web Page'