---
# tasks file for webserver
  - name: Template a file to /etc/httpd/conf/httpd.conf
    template:
      src: index.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - restart apache
  - name: Template a file to /var/www/html/
    template:
      src: httpd.j2
      dest: /var/www/html/
  - name: Install the httpd apps
    yum: name={{package}}
    when: ansible_os_family == "RedHat"
  - name: start the httpd service
    service: name={{service}} state=started
  - name: Add the user 'ambikram' with a specific uid and a primary group of 'admin'
    user: name=ambikram group=deploy
  - name: Display my name
    debug: msg={{username}}
  - name: Copy the file to /tmp
    copy: dest=/tmp/ src="test.sh"
  - name: Execute the script in remote
    shell: sh /tmp/test.sh >>index.html
    register: result
  - name: Show the result
    debug: var=result.stdout.split('/n')
  - name: Create a new group
    group: name=deloitte
  - name: Add the user 'deploy' with a specific uid and a primary group of 'admin'
    user: name=deploy group=deloitte
  - name: Install common software requirements
    yum: name={{ item }}
    with_items:
       - git
       - ntp
       - vim
